---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- marketplace-fe-portal-deployment.yaml
- marketplace-fe-portal-service.yaml
- marketplace-fe-portal-ingress.yaml
namespace: frontend
images: