apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal
  name: portal-nodeport-svc
  namespace: frontend
spec:
  ports:
  - nodePort: 32122
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: portal
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portal
  name: marketplace-fe-portal
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: portal
    spec:
      containers:
      - image: 192.168.110.135:5000/portal:d5d89d26
        name: portal
        resources:
          limits:
            cpu: 25m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
