apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal
  name: portal-nodeport-svc
  namespace: frontend
spec:
  ports:
  - nodePort: 32122
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: portal
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portal
  name: marketplace-fe-portal
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: portal
    spec:
      containers:
      - image: 192.168.110.135:5000/portal:2e5b8720
        name: portal
        resources:
          limits:
            cpu: 256m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservice
  namespace: frontend
spec:
  ingressClassName: nginx
  rules:
  - host: kubernetes.my.local
    http:
      paths:
      - backend:
          service:
            name: portal-nodeport-svc
            port:
              number: 80
        path: /
        pathType: Prefix
