apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal
  name: portal-nodeport-svc
  namespace: frontend
spec:
  ports:
  - nodePort: 32122
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: portal
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portal
  name: marketplace-fe-portal
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: portal
    spec:
      containers:
      - image: 192.168.110.135:5000/portal:698
        name: portal
