apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal
  name: portal-nodeport-svc
  namespace: frontend
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32121
  selector:
    app: portal
  type: NodePort